"""
Obsidian Markdown Saver
Creates formatted markdown notes for Obsidian
"""
import shutil
from datetime import datetime
from pathlib import Path
from typing import List

import config
from modules.models import Topic


def create_markdown_note(
    topics: List[Topic],
    summary: str,
    output_path: Path,
    images_dir: Path
) -> str:
    """
    Create a formatted Obsidian markdown note

    Args:
        topics: List of Topic objects
        summary: Chinese summary text
        output_path: Path to save markdown file
        images_dir: Directory containing generated images

    Returns:
        Path to created markdown file
    """
    print("📝 Creating Obsidian markdown note...")

    today = datetime.now()
    date_str = today.strftime("%Y-%m-%d")
    date_display = today.strftime("%B %d, %Y")

    # Build markdown content
    md_lines = [
        f"# AI News Digest - {date_display}",
        "",
        f"> Auto-generated on {today.strftime('%Y-%m-%d %H:%M')}",
        "> Source: Reddit AI Communities",
        "",
        "---",
        "",
        "## 📊 Trend Summary",
        "",
        summary,
        "",
        "---",
        "",
        f"## 🔥 Top {len(topics)} Topics",
        "",
    ]

    # Add each topic
    for i, topic in enumerate(topics, 1):
        md_lines.extend([
            f"### {i}. {topic.title}",
            "",
        ])

        # Add image if available
        if topic.image_filename:
            md_lines.extend([
                f"![[images/{topic.image_filename}]]",
                "",
            ])

        md_lines.extend([
            f"**Importance**: {'⭐' * min(topic.importance, 10)}",
            "",
            topic.description,
            "",
            f"**Keywords**: {', '.join(topic.keywords)}",
            "",
            "---",
            "",
        ])

    # Add footer
    md_lines.extend([
        "## 📌 About",
        "",
        "This report was auto-generated by Meridian:",
        "1. Collected AI-related posts from Reddit",
        "2. Summarized using Claude API",
        "3. Extracted Top 10 important topics",
        "4. Generated professional images for each topic",
        "",
        f"#AI #DailyDigest #AutoGenerated #{date_str.replace('-', '')}",
    ])

    # Write markdown file
    content = "\n".join(md_lines)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")

    print(f"✅ Markdown saved: {output_path}")

    return str(output_path)


def copy_to_obsidian(
    markdown_path: Path,
    images_dir: Path,
    obsidian_vault: Path
) -> bool:
    """
    Copy generated files to Obsidian vault

    Args:
        markdown_path: Path to markdown file
        images_dir: Directory with generated images
        obsidian_vault: Path to Obsidian vault

    Returns:
        True if successful
    """
    if not obsidian_vault.exists():
        print(f"⚠ Obsidian vault not found: {obsidian_vault}")
        return False

    try:
        # Create date-based folder
        today = datetime.now().strftime("%Y-%m-%d")
        dest_dir = obsidian_vault / f"AI-News-{today}"
        dest_dir.mkdir(parents=True, exist_ok=True)

        # Copy markdown
        shutil.copy2(markdown_path, dest_dir / "index.md")

        # Copy images
        dest_images = dest_dir / "images"
        if images_dir.exists():
            shutil.copytree(images_dir, dest_images, dirs_exist_ok=True)

        print(f"✅ Copied to Obsidian: {dest_dir}")
        return True

    except Exception as e:
        print(f"⚠ Copy failed: {e}")
        return False


if __name__ == "__main__":
    # Test
    test_topics = [
        Topic(
            title="GPT-5 即将发布",
            title_en="GPT-5 Release",
            description="OpenAI 预计将在近期发布新一代语言模型。",
            keywords=["GPT-5", "OpenAI"],
            importance=9,
            image_filename="topic_01.png"
        )
    ]

    test_summary = "本周AI领域最热门的话题是GPT-5的发布传闻..."

    output = Path("./test_output/ai-news.md")
    create_markdown_note(test_topics, test_summary, output, Path("./test_output/images"))
